name: 'Publish to PowerShell Gallery'
description: 'Publishing your module to the PowerShell Gallery'
author: 'Shawn Melton'
inputs:
  tags:
    description: 'Tags to apply to your module in PowerShell Gallery. Should be comma list.'
    required: true
  apiKey:
    description: 'PowerShell Gallery API Key for publishing to your account'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.tags }}
    - ${{ inputs.apiKey }}
branding:
  icon: 'upload'
  color: 'blue'