name: test
on: [push]
jobs:
  testit:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
      - name: testit
        uses: wsmelton/publish-powershell-module@beta
        with:
          tags: test1
          apiKey: ${{secrets.APIKEY}}